# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\rstudentcourse\"\x07\n\x05\x45mpty\"B\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0e\n\x06\x63ourse\x18\x04 \x01(\t\"U\n\x06\x43ourse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63ourse_name\x18\x02 \x01(\t\x12\x13\n\x0b\x63ourse_code\x18\x03 \x01(\t\x12\x15\n\rstudent_count\x18\x04 \x01(\x05\"A\n\x15StudentCourseResponse\x12(\n\x08students\x18\x01 \x03(\x0b\x32\x16.studentcourse.Student\"B\n\x18\x43ourseStatisticsResponse\x12&\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x15.studentcourse.Course\"P\n\rStudentUpdate\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0e\n\x06\x63ourse\x18\x04 \x01(\t2\x8f\x02\n\x14StudentCourseService\x12R\n\x14GetStudentCourseData\x12\x14.studentcourse.Empty\x1a$.studentcourse.StudentCourseResponse\x12T\n\x13GetCourseStatistics\x12\x14.studentcourse.Empty\x1a\'.studentcourse.CourseStatisticsResponse\x12M\n\x15StreamRealTimeUpdates\x12\x14.studentcourse.Empty\x1a\x1c.studentcourse.StudentUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_STUDENT']._serialized_start=43
  _globals['_STUDENT']._serialized_end=109
  _globals['_COURSE']._serialized_start=111
  _globals['_COURSE']._serialized_end=196
  _globals['_STUDENTCOURSERESPONSE']._serialized_start=198
  _globals['_STUDENTCOURSERESPONSE']._serialized_end=263
  _globals['_COURSESTATISTICSRESPONSE']._serialized_start=265
  _globals['_COURSESTATISTICSRESPONSE']._serialized_end=331
  _globals['_STUDENTUPDATE']._serialized_start=333
  _globals['_STUDENTUPDATE']._serialized_end=413
  _globals['_STUDENTCOURSESERVICE']._serialized_start=416
  _globals['_STUDENTCOURSESERVICE']._serialized_end=687
# @@protoc_insertion_point(module_scope)
