# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analytics_pb2 as analytics__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StudentCourseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStudentCourseData = channel.unary_unary(
                '/studentcourse.StudentCourseService/GetStudentCourseData',
                request_serializer=analytics__pb2.Empty.SerializeToString,
                response_deserializer=analytics__pb2.StudentCourseResponse.FromString,
                _registered_method=True)
        self.GetCourseStatistics = channel.unary_unary(
                '/studentcourse.StudentCourseService/GetCourseStatistics',
                request_serializer=analytics__pb2.Empty.SerializeToString,
                response_deserializer=analytics__pb2.CourseStatisticsResponse.FromString,
                _registered_method=True)
        self.StreamRealTimeUpdates = channel.unary_stream(
                '/studentcourse.StudentCourseService/StreamRealTimeUpdates',
                request_serializer=analytics__pb2.Empty.SerializeToString,
                response_deserializer=analytics__pb2.StudentUpdate.FromString,
                _registered_method=True)


class StudentCourseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStudentCourseData(self, request, context):
        """Aggregated data of students and their enrolled courses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourseStatistics(self, request, context):
        """Statistics on course enrollment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRealTimeUpdates(self, request, context):
        """Real-time data push using RabbitMQ
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentCourseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStudentCourseData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentCourseData,
                    request_deserializer=analytics__pb2.Empty.FromString,
                    response_serializer=analytics__pb2.StudentCourseResponse.SerializeToString,
            ),
            'GetCourseStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseStatistics,
                    request_deserializer=analytics__pb2.Empty.FromString,
                    response_serializer=analytics__pb2.CourseStatisticsResponse.SerializeToString,
            ),
            'StreamRealTimeUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRealTimeUpdates,
                    request_deserializer=analytics__pb2.Empty.FromString,
                    response_serializer=analytics__pb2.StudentUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'studentcourse.StudentCourseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('studentcourse.StudentCourseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StudentCourseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStudentCourseData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studentcourse.StudentCourseService/GetStudentCourseData',
            analytics__pb2.Empty.SerializeToString,
            analytics__pb2.StudentCourseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCourseStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studentcourse.StudentCourseService/GetCourseStatistics',
            analytics__pb2.Empty.SerializeToString,
            analytics__pb2.CourseStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRealTimeUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/studentcourse.StudentCourseService/StreamRealTimeUpdates',
            analytics__pb2.Empty.SerializeToString,
            analytics__pb2.StudentUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
